### ISSUE TITLE
Binary representation creation failure (extremely sparse result)

### ISSUE THREAD

**Issue by rwiesbach** [JoshuaMart/HIBP_PasswordList_Slimmer#1]
Hey there,

It took about 5.5 hours to convert a current hibp ntlm dataset obtained by the official downloader. As you describe about 19 GB being compressed to 10 GB I expected roughly from 29 GB to about 15 GB, but the resulting file is only about 3GB. Looking at it in a hex editor the file looks extremely sparse. Using fastest 7z compression it is compressed down to 1MB (!)

I used the windows version of the slimmer/converter.

**Comment by JoshuaMart** [comment]
Hi,
this repository is no longer working as expected with the new password file format.

The tool will not be updated, however, so I'm going to archive the repository.

Regards
